### ISSUE TITLE
Hi! Are there any sample projects using this boilerplate we can look at?

### ISSUE THREAD

**Issue by sniebauer** [Cloudhuset/Zendesk-React-App-Boilerplate#18]
Hi! I'm a bit newer to React but love the ZAF Client for projects. I was wondering if there are any sample projects that utilize your boilerplate a bit more to show how to get other pieces of information using the ZAF client?

Even just some more code examples other than the `users` call in the current code would very helpful. Thanks so much!

**Comment by Herlevsen** [comment]
Hi @sniebauer 

Please reference the ZAF client documentation https://developer.zendesk.com/apps/docs/core-api/client_api#content to find out how to get other pieces of data. Wherever you need to use the client you just import it and use it.

Also, I would advise you not to use redux. If you need global state, use reacts context api instead. Redux will probably be removed from this boilerplate at some point, since it is rarely needed for small apps.
